### ISSUE TITLE
Presto Foundation TSC Nomination Period Extension

### ISSUE THREAD

**Issue by micmarti85** [prestodb/tsc#100]
The purpose of this issue is to allow Nominees from [Issue #97](https://github.com/prestodb/tsc/issues/97) to publicly accept their nomination and complete the [required information](https://github.com/prestodb/tsc/issues/97#issue-1497302764). This supplementary nomination period will remain open through 1/16/2023 @ 12:00am EST and will be followed by a week of voting conducted using OpaVote.

**Please see timeline below for exact dates and times.**
Nomination Period Extension: 1/11/2023-1/16/2023 @ 12:00am EST
Voting Period: 1/16/2023- 1/23/2023 @ 12:00am EST
Winner Announced: 1/23/2023 @ 12:00pm EST

**Nomination statements:**
[Beinan Wang (@beinan)](https://github.com/prestodb/tsc/issues/97#issuecomment-1367537701)
[James Sun (@highker)](https://github.com/prestodb/tsc/issues/97#issuecomment-1376000609)
[Aditi Pandit (@aditi-pandit)](https://github.com/prestodb/tsc/issues/97#issuecomment-1376726144)

If anyone has any questions or concerns please let me know.

**Comment by micmarti85** [comment]
[@beinan](https://github.com/beinan) @highker @aditi-pandit @tdcmeehan @StevenMih @apc999

**Comment by aditi-pandit** [comment]
GitHub username: aditi-pandit
Email: [aditi@ahana.io](mailto:aditi@ahana.io)

**Please provide 2-3 sentences on your involvement in the Presto project**

I have been involved with the Prestissimo and Velox projects since 2021.

Core projects :

TPC-H coverage in Prestissimo (2021) : Put together a test TPC-H query workload in Prestissimo and get it operational. I implemented the Date type in Velox/Prestissimo, LIKE operator and did other bug fixes for this.

Window functions in Prestissimo (2022) : I lead a project to implement Window functions in Velox/Prestissimo. The core of the functionality :rank/value/aggregates as windows was completed in 2021. In 2022 I will focus on performance and spill to disk issues.

TPC-H micro benchmarking (2022) : Worked along with an Ahana team-mate (pramodsatya) to add TPC-H micro-benchmark queries to Velox. Did performance evaluation against DuckDB.

I presented in PrestoCon Dec 2022 on "Building Large Scale Query Operators for Prestissimo" based on my experience with Window operator development in 2022.

**Please provide 3-6 sentences on what you aspire to achieve on the TSC**
Based on my current and previous experiences in data infrastructure products there are few areas I want to influence in Presto:

i) Prestissimo : Since the last 2-3 years there has been an initiative to improve price performance of Presto by moving to a C++ based query execution engine. This development is in line with the industry and other similar projects like Photon at Databricks. One of the goals I want to influence is the advancement of Presto/Velox in the Open Cloud platforms: S3 on AWS, etc. This includes SQL coverage, performance and other functionality.

ii) Advanced analytics : In previous work experiences I've worked on advanced Database features in the query optimizer/extensibility areas for improving the analytics capabilities of SQL engines. I hope to provide thought leadership in this area to the Presto community.

iii) Community work : I want to contribute to more helpful documentation, customer case studies in Presto. At Ahana we care about great production deployment experiences for customers and I hope to carry that forward in a way to influence the open source Presto product.

**Do you currently hold any formal leadership roles within the Presto community?**
Yes, Presto Code Owner Committer (Prestissimo).

**Do you commit to attending the monthly TSC calls?**
Yes.

**Comment by highker** [comment]
I confirm the nomination from @tdcmeehan. Here is a short blurb of my contribution to Presto in 2022

1. Served as the uber TL of Presto team at Meta pushing for major directions including (1) presto on spark and (2) velox on presto. Many projects are spun off from these two including historical-based optimizer, adaptive query execution, prestissimo, velox integration with presto on spark, etc.

2. [Top reviewer](https://insights.lfx.linuxfoundation.org/projects/presto/dashboard;subTab=technical;v=pull-request-management%2Fgithub-pr%2Freviews?filter=%23%2Fdashboard%2F0d994010-9d6f-11eb-9005-3930817a030d%3Fembed%3Dtrue%26_g%3D(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:%27now-1y%27,to:%27now%27))%26_a%3D(description:%27Github%2520PR%2520Review%2520Dashboard%27,filters:!((%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:github_issues,key:author_bot,negate:!t,params:(query:!t),type:phrase),query:(match_phrase:(author_bot:!t)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(title:Filter),gridData:(h:18,i:ff3b6778-2cba-4118-b50e-3359e83ec6e4,w:9,x:0,y:0),id:%2753384b40-a3ad-11eb-94e8-4323c8335d1a%27,panelIndex:ff3b6778-2cba-4118-b50e-3359e83ec6e4,title:Filter,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:Summary),gridData:(h:12,i:%278b500eec-31ac-4dbb-a377-5ed54eb3b753%27,w:12,x:9,y:0),id:%273955c410-9d62-11eb-9005-3930817a030d%27,panelIndex:%278b500eec-31ac-4dbb-a377-5ed54eb3b753%27,title:Summary,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27Repos%2520By%2520Review%2520Activity%27),gridData:(h:18,i:%276eca6b85-cbac-4b94-9788-d16cf56e4215%27,w:12,x:21,y:0),id:%2716fc8090-ad14-11eb-b42d-29bb7e46b0a1%27,panelIndex:%276eca6b85-cbac-4b94-9788-d16cf56e4215%27,title:%27Repos%2520By%2520Review%2520Activity%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27PR%2520Review%2520States%27),gridData:(h:15,i:c8fe7a1b-801a-4365-b2d8-c35dcbaa3aeb,w:15,x:33,y:0),id:%274f0932c0-9d66-11eb-94e8-4323c8335d1a%27,panelIndex:c8fe7a1b-801a-4365-b2d8-c35dcbaa3aeb,title:%27PR%2520Review%2520States%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27About%2520Summary%27),gridData:(h:6,i:%2704c8d128-6d4d-43ee-aeac-66346db58a34%27,w:12,x:9,y:12),id:e000d110-acda-11eb-bd79-f3db3ff39743,panelIndex:%2704c8d128-6d4d-43ee-aeac-66346db58a34%27,title:%27About%2520Summary%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27About%2520PR%2520Review%2520States%27),gridData:(h:3,i:db15b6ee-bf9b-480e-98cc-4e26dfac6fa9,w:15,x:33,y:15),id:%275aa25820-ace1-11eb-b42d-29bb7e46b0a1%27,panelIndex:db15b6ee-bf9b-480e-98cc-4e26dfac6fa9,title:%27About%2520PR%2520Review%2520States%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27Median%2520Time%2520To%2520First%2520Approval%27),gridData:(h:16,i:%274045abd7-25bf-466e-a978-6c1faa14931b%27,w:16,x:17,y:18),id:%27839da990-a36e-11eb-94e8-4323c8335d1a%27,panelIndex:%274045abd7-25bf-466e-a978-6c1faa14931b%27,title:%27Median%2520Time%2520To%2520First%2520Approval%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27PRs%2520Merged%2520Without%2520Approval%27),gridData:(h:16,i:%2798eaab05-ae30-4245-8ce7-0af4ec455a60%27,w:15,x:33,y:18),id:e309e620-a439-11eb-9005-3930817a030d,panelIndex:%2798eaab05-ae30-4245-8ce7-0af4ec455a60%27,title:%27PRs%2520Merged%2520Without%2520Approval%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27Median%2520Time%2520To%2520First%2520Review%27),gridData:(h:16,i:%279bc5126d-ac68-475e-a81e-a113fcd213bd%27,w:17,x:0,y:18),id:ad25de90-9d65-11eb-94e8-4323c8335d1a,panelIndex:%279bc5126d-ac68-475e-a81e-a113fcd213bd%27,title:%27Median%2520Time%2520To%2520First%2520Review%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27About%2520Median%2520Time%2520To%2520First%2520Approval%27),gridData:(h:4,i:%2770705243-ec26-425d-a26a-2620714a15a2%27,w:16,x:17,y:34),id:d17acc70-aceb-11eb-b42d-29bb7e46b0a1,panelIndex:%2770705243-ec26-425d-a26a-2620714a15a2%27,title:%27About%2520Median%2520Time%2520To%2520First%2520Approval%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27About%2520PRs%2520Merged%2520Without%2520Approval%27),gridData:(h:4,i:%272a797932-4967-40c3-b621-0319d2e55572%27,w:15,x:33,y:34),id:a77df370-acf0-11eb-b42d-29bb7e46b0a1,panelIndex:%272a797932-4967-40c3-b621-0319d2e55572%27,title:%27About%2520PRs%2520Merged%2520Without%2520Approval%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27About%2520Median%2520Time%2520To%2520First%2520Review%27),gridData:(h:4,i:%27581c1056-f58d-42fe-8b67-32e1ca253421%27,w:17,x:0,y:34),id:%2760b56470-ace9-11eb-bd79-f3db3ff39743%27,panelIndex:%27581c1056-f58d-42fe-8b67-32e1ca253421%27,title:%27About%2520Median%2520Time%2520To%2520First%2520Review%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27Organization%2520PR%2520Review%2520Summary%27),gridData:(h:20,i:%278e0d53fb-9826-4378-8292-5189991f99f6%27,w:23,x:25,y:38),id:ce23c960-9d6d-11eb-9005-3930817a030d,panelIndex:%278e0d53fb-9826-4378-8292-5189991f99f6%27,title:%27Organization%2520PR%2520Review%2520Summary%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27Repository%2520PR%2520Review%2520Summary%27,vis:(params:(sort:(columnIndex:1,direction:!n)))),gridData:(h:20,i:%273281ee34-8d2d-428c-82cf-f12b7e0350e1%27,w:25,x:0,y:38),id:%27079360e0-9d6c-11eb-9005-3930817a030d%27,panelIndex:%273281ee34-8d2d-428c-82cf-f12b7e0350e1%27,title:%27Repository%2520PR%2520Review%2520Summary%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27Reviewer%2520Activity%27),gridData:(h:23,i:%274a80fa72-21d4-4a61-a0b8-69ca692208a7%27,w:24,x:0,y:58),id:b8bcb320-a1e1-11eb-9005-3930817a030d,panelIndex:%274a80fa72-21d4-4a61-a0b8-69ca692208a7%27,title:%27Reviewer%2520Activity%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27Latest%2520PRs%2520Review%2520Activity%27),gridData:(h:23,i:%27735aa32c-d511-4f81-9190-585185c5104c%27,w:24,x:24,y:58),id:%273a38e730-abff-11eb-bd79-f3db3ff39743%27,panelIndex:%27735aa32c-d511-4f81-9190-585185c5104c%27,title:%27Latest%2520PRs%2520Review%2520Activity%27,type:visualization,version:%277.6.2%27)),query:(language:kuery,query:%27%27),timeRestore:!f,title:%27Github%2520Review%2520Dashboard%27,viewMode:view)&time=%7B%22from%22:%22now-1y%22,%22type%22:%22datemath%22,%22to%22:%22now%22%7D) of presto community: 300+ PR reviews

**Comment by beinan** [comment]
I confirm the nomination from @apc999 .     Also put some of the required information as below. 

Please provide 3-6 sentences on what he aspire to achieve on the TSC

1. Promote presto as a major compute engine besides spark and flink for datalakes (iceberg and hudi)
2. Promote presto to the field of sub-second computing jobs (with caching, druid-connector and etc.)
3. Let more excellent developers join the prestodb community, this is actually what I have been doing, and have some results
4. Make presto easier to use and reduce the burden of maintenance -- I'm working on a new tool to manage and visualize the running presto cluster which would be open sourced later.


Does he currently hold any formal leadership roles within the Presto community?
No

Does he commit to attending the monthly TSC calls?
Yes

**Comment by micmarti85** [comment]
Results are in, thank  you to all who participated.

James Sun has been elected as a TSC Member from 1/23/23-1/23/24



[@beinan](https://github.com/beinan) @highker @aditi-pandit @tdcmeehan @StevenMih @apc999
