### ISSUE TITLE
Finalize how to add a committer

### ISSUE THREAD

**Issue by caniszczyk** [prestodb/tsc#4]
https://github.com/prestodb/presto/wiki/How-to-become-a-Presto-committer%3F

**Comment by caniszczyk** [comment]
Can we please solidify this in a file and list folks with affiliations

**Comment by brianwarner** [comment]
Certainly - reading the technical charter, I think the only thing which is missing from this text is the procedure by which new committers are added or removed (2/3 vote of TSC).  

Does it make sense to add the updated contents of this wiki page to CONTRIBUTING.md, so that the content is replicated across all repos?  I think it does?

**Comment by brianwarner** [comment]
I presumptively added both the updated contents of that file and the list of committers + affiliations to the PR in .github: https://github.com/prestodb/.github/blob/add-contributing/CONTRIBUTING.md

**Comment by brianwarner** [comment]
I think we can resolve this one now. The committers are appointed by the project, and TSC members are elected from the committers, and this is documented in the project repo/TSC README/TSC charter.
